# Generated by Django 4.2 on 2023-11-08 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '__first__'),
        ('users', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', to_field='user_id'),
        ),
        migrations.AddField(
            model_name='companiesadmins',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_to_admin', to='companies.companies'),
        ),
        migrations.AddField(
            model_name='companiesadmins',
            name='isadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='users.users'),
        ),
        migrations.AddField(
            model_name='companies',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.address'),
        ),
        migrations.AddField(
            model_name='companies',
            name='phones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.phone'),
        ),
        migrations.AlterUniqueTogether(
            name='workson',
            unique_together={('user', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='companiesadmins',
            unique_together={('company', 'isadmin')},
        ),
    ]
