# Generated by Django 4.2 on 2023-11-10 13:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companies_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='phones',
        ),
        migrations.AddField(
            model_name='companies',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='null', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
