# Generated by Django 4.2 on 2023-12-19 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChats',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=256)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companies')),
            ],
            options={
                'db_table': 'group_chats',
            },
        ),
        migrations.CreateModel(
            name='GroupChatsAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.workson')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupchats.groupchats')),
            ],
            options={
                'db_table': 'group_chats_admins',
            },
        ),
        migrations.CreateModel(
            name='GroupChatMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupchats.groupchats')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.workson')),
            ],
            options={
                'db_table': 'group_chats_members',
            },
        ),
    ]
