# Generated by Django 4.2 on 2023-12-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchats',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
