# Generated by Django 4.2 on 2023-12-26 15:15

import apps.groupchats.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupchats', '0002_alter_groupchats_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatmembers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupchatsadmins',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='GroupChatConversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.groupchats.models.get_upload_path)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupchats.groupchats')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groupchats.groupchatmembers')),
            ],
            options={
                'db_table': 'group_chat_conversation',
            },
        ),
    ]
