# Generated by Django 4.2 on 2023-12-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '__first__'),
        ('groupchats', '0004_groupchatconversation_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatconversation',
            name='send_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='groupchatmembers',
            unique_together={('group', 'member')},
        ),
    ]
