# Generated by Django 4.2 on 2023-12-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_privatechat_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechat',
            name='date',
        ),
        migrations.AddField(
            model_name='privatechat',
            name='send_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
