# Generated by Django 4.2 on 2023-12-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_privatechat_date_privatechat_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechat',
            name='send_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
