# Generated by Django 5.0.5 on 2024-05-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_privatechat_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechat',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
