# Generated by Django 4.2 on 2023-11-08 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersCredentials',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'users_credentials',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.userscredentials')),
                ('firstname', models.CharField(max_length=32)),
                ('midname', models.CharField(blank=True, max_length=32, null=True)),
                ('lastname', models.CharField(max_length=32)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('occupation', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(max_length=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_image')),
                ('about', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=64)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('phones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.phone', unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UniversityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('graduation', models.DateField()),
                ('degree', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'university_details',
            },
        ),
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('graduation', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'education_details',
            },
        ),
    ]
