# Generated by Django 4.2 on 2023-11-09 12:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_gender_alter_users_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phones',
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='null', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
