# Generated by Django 4.2 on 2023-12-06 09:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_remove_companies_phones_companies_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsPrivate',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('title', models.TextField(blank=True, max_length=64, null=True)),
                ('body', models.TextField()),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts_private')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companies')),
            ],
            options={
                'db_table': 'posts_private',
            },
        ),
    ]
